import "./globals.css";
import SideNav from "./SideNav";
import TopNav from "./TopNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-900 text-zinc-200 ">
        <div className=" flex flex-col h-screen w-screen overflow-x-hidden">
          <TopNav />
          <div className="flex flex-1 ">
            <div className="">
              <SideNav />
            </div>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
