import { Metadata } from "next"
import "./globals.css"
import SideNav from "./SideNav"
import TopNav from "./TopNav"
import { Roboto } from "next/font/google"
import Providers from "@/components/Providers"
import { cn } from "@/lib/utils"
const roboto = Roboto({
  variable: "--font-inter",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  style: ["normal"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={cn(
        "bg-white dark:bg-gray-800 text-slate-900 antialiased",
        roboto.variable
      )}
    >
      <body className="font-Roboto min-h-screen hide-scrollbar antialiased bg-white dark:bg-slate-900">
        <Providers>
          <div className="pt-20">
            <TopNav />
            <div className="flex flex-1 ">
              <SideNav />
              <div>{children}</div>
            </div>
          </div>
        </Providers>
        {/* Allow for more height on mobile devices */}
        <div className="h-40 md:hidden" />
      </body>
    </html>
  )
}
