import "./globals.css";
import SideNav from "./SideNav";
import TopNav from "./TopNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-900 text-zinc-200 ">
        <div className="border-2 border-green-500  flex flex-col h-screen w-screen ">
          <TopNav />
          <div className="flex border-2 border-purple-300 flex-1">
            <SideNav />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
